name: main

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    name: Build
    if: "!contains(github.event.commits[0].message, 'ci skip')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup golang v1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13

      - name: Build all
        env:
          DEPLOYER_TOKEN: ${{secrets.GH_TOKEN}}
        run: |
          PB_REL="https://github.com/protocolbuffers/protobuf/releases"
          curl -LO $PB_REL/download/v3.17.0/protoc-3.17.0-linux-x86_64.zip
          unzip protoc-3.17.0-linux-x86_64.zip -d $HOME/.local
          curl -LO https://github.com/bufbuild/buf/releases/download/v0.42.1/buf-Linux-x86_64.tar.gz
          tar xvzf buf-Linux-x86_64.tar.gz
          cp buf/bin/* $HOME/.local/bin/
          export GO111MODULE=on
          go get -u google.golang.org/protobuf/cmd/protoc-gen-go \
            google.golang.org/grpc/cmd/protoc-gen-go-grpc \
            github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway \
            github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2
          export PATH="$PATH:$HOME/.local/bin:$(go env GOPATH)/bin"
          buf generate
          # Update blue-sdk-go:
          WORKSPACE_ROOT=$PWD
          cd /tmp/ && git clone https://github.com/alphauslabs/blue-sdk-go && cd blue-sdk-go
          cp -rv $WORKSPACE_ROOT/generated/go/* . && git status
          git config user.email "dev@mobingi.com"
          git config user.name "mobingideployer"
          git add . && git commit -am "$GITHUB_REF $GITHUB_SHA" || true
          git remote add origin-tmp https://$DEPLOYER_TOKEN@github.com/alphauslabs/blue-sdk-go.git > /dev/null 2>&1
          git push --set-upstream origin-tmp
          # Update OpenAPI docs repo:
          cd /tmp/ && git clone https://github.com/alphauslabs/blueapidocs && cd blueapidocs
          cp $WORKSPACE_ROOT/openapiv2/apidocs.swagger.json ./swagger.yaml && git status
          git add . && git commit -am "$GITHUB_REF $GITHUB_SHA" || true
          git remote add origin-tmp https://$DEPLOYER_TOKEN@github.com/alphauslabs/blueapidocs.git > /dev/null 2>&1
          git push --set-upstream origin-tmp
